-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table categoria_receta_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  constraint pk_categoria_receta_model primary key (id)
);

create table pasos_receta_model (
  id                            bigint generated by default as identity not null,
  pasos_aseguir                 varchar(255),
  parent_receta_id              bigint,
  constraint pk_pasos_receta_model primary key (id)
);

create table receta_model (
  id                            bigint generated by default as identity not null,
  name                          varchar(255),
  time                          integer,
  dificultad                    integer,
  video_id                      bigint,
  version                       bigint not null,
  when_created                  timestamp not null,
  when_modified                 timestamp not null,
  constraint uq_receta_model_video_id unique (video_id),
  constraint pk_receta_model primary key (id)
);

create table receta_model_categoria_receta_model (
  receta_model_id               bigint not null,
  categoria_receta_model_id     bigint not null,
  constraint pk_receta_model_categoria_receta_model primary key (receta_model_id,categoria_receta_model_id)
);

create table video_receta_model (
  id                            bigint generated by default as identity not null,
  video_url                     varchar(255),
  constraint pk_video_receta_model primary key (id)
);

-- foreign keys and indices
create index ix_pasos_receta_model_parent_receta_id on pasos_receta_model (parent_receta_id);
alter table pasos_receta_model add constraint fk_pasos_receta_model_parent_receta_id foreign key (parent_receta_id) references receta_model (id) on delete restrict on update restrict;

alter table receta_model add constraint fk_receta_model_video_id foreign key (video_id) references video_receta_model (id) on delete restrict on update restrict;

create index ix_receta_model_categoria_receta_model_receta_model on receta_model_categoria_receta_model (receta_model_id);
alter table receta_model_categoria_receta_model add constraint fk_receta_model_categoria_receta_model_receta_model foreign key (receta_model_id) references receta_model (id) on delete restrict on update restrict;

create index ix_receta_model_categoria_receta_model_categoria_receta_m_2 on receta_model_categoria_receta_model (categoria_receta_model_id);
alter table receta_model_categoria_receta_model add constraint fk_receta_model_categoria_receta_model_categoria_receta_m_2 foreign key (categoria_receta_model_id) references categoria_receta_model (id) on delete restrict on update restrict;


-- !Downs

-- drop all foreign keys
alter table pasos_receta_model drop constraint if exists fk_pasos_receta_model_parent_receta_id;
drop index if exists ix_pasos_receta_model_parent_receta_id;

alter table receta_model drop constraint if exists fk_receta_model_video_id;

alter table receta_model_categoria_receta_model drop constraint if exists fk_receta_model_categoria_receta_model_receta_model;
drop index if exists ix_receta_model_categoria_receta_model_receta_model;

alter table receta_model_categoria_receta_model drop constraint if exists fk_receta_model_categoria_receta_model_categoria_receta_m_2;
drop index if exists ix_receta_model_categoria_receta_model_categoria_receta_m_2;

-- drop all
drop table if exists categoria_receta_model;

drop table if exists pasos_receta_model;

drop table if exists receta_model;

drop table if exists receta_model_categoria_receta_model;

drop table if exists video_receta_model;

